#!/usr/bin/env bash
# Build or verify the committed MU-plugin bundle.

set -euo pipefail

cd "$(dirname "$0")"

SOURCE_DIR="$PWD"
MU_DIR="$PWD/../../wp/wp-content/mu-plugins"
TARGET_PAYLOAD="$MU_DIR/serverlesswp-stream-wrapper"
TARGET_LOADER="$MU_DIR/serverlesswp-stream-wrapper.php"
CHECK_ONLY=false

if [ "${1:-}" = "--check" ]; then
    CHECK_ONLY=true
fi

STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT
chmod 755 "$STAGING"

PAYLOAD="$STAGING/payload"
LOADER="$STAGING/loader.php"
mkdir -p "$PAYLOAD"

echo "==> Installing production dependencies"
cp composer.json composer.lock "$PAYLOAD/"

# Composer dependencies require ext-simplexml.
if command -v docker >/dev/null 2>&1; then
    docker run --rm -u "$(id -u):$(id -g)" -e COMPOSER_HOME=/tmp/composer \
        -v "$PAYLOAD:/app" -w /app composer:2 \
        install --no-dev --no-interaction --quiet
elif command -v composer >/dev/null 2>&1; then
    (cd "$PAYLOAD" && composer install --no-dev --no-interaction --quiet)
else
    echo "Need either docker or composer on PATH." >&2
    exit 1
fi

echo "==> Assembling plugin"
cp "$SOURCE_DIR/serverlesswp-stream-wrapper.php" "$PAYLOAD/"
cp -R "$SOURCE_DIR/bootstrap" "$PAYLOAD/bootstrap"
cp -R "$SOURCE_DIR/src" "$PAYLOAD/src"

cat > "$PAYLOAD/README.txt" <<'EOF'
Generated by packages/serverlesswp-stream-wrapper/build-plugin.sh — do not edit here.

Edit packages/serverlesswp-stream-wrapper/ and re-run that script.
Everything in this directory is overwritten.
EOF

cp "$SOURCE_DIR/bootstrap/mu-loader.php" "$LOADER"

if [ "$CHECK_ONLY" = true ]; then
    status=0
    if [ ! -d "$TARGET_PAYLOAD" ] || [ ! -f "$TARGET_LOADER" ]; then
        echo "FAIL: the committed plugin copy is missing." >&2
        status=1
    else
        diff -r "$PAYLOAD" "$TARGET_PAYLOAD" || status=1
        diff "$LOADER" "$TARGET_LOADER" || status=1
    fi

    if [ "$status" -ne 0 ]; then
        echo "FAIL: run ./build-plugin.sh and commit the result." >&2
        exit 1
    fi
    echo "OK: the committed plugin copy is current."
    exit 0
fi

mkdir -p "$MU_DIR"
rm -rf "$TARGET_PAYLOAD"
cp -R "$PAYLOAD" "$TARGET_PAYLOAD"
cp "$LOADER" "$TARGET_LOADER"

echo "==> Built $(find "$TARGET_PAYLOAD" -type f | wc -l) files, $(du -sh "$TARGET_PAYLOAD" | cut -f1) at"
echo "    ${TARGET_PAYLOAD}"
