#!/usr/bin/env bash
#
# Assembles the deployable copy of this plugin under wp/wp-content/mu-plugins.
#
# It ships as a must-use plugin so it is active whenever WP_STREAM_PROVIDER is
# set, with no activation step in wp-admin. A half-configured site — wrapper
# registered by the prepend, WordPress hooks inactive — would break thumbnails
# and 404 uploads with nothing to explain why.
#
# Two entries are produced, because WordPress only auto-loads .php files
# sitting directly in mu-plugins:
#
#   wp-content/mu-plugins/wp-alt-streamwrapper.php   loader
#   wp-content/mu-plugins/wp-alt-streamwrapper/      runtime files + vendor
#
# The copy is committed because the platforms ServerlessWP deploys to have no
# PHP or Composer at build time, and Vercel/Netlify only bundle files under
# wp/. Tests, the Docker harness and dev dependencies stay in this directory.
#
#   ./build-plugin.sh          rebuild the copy
#   ./build-plugin.sh --check  exit non-zero if the committed copy is stale
#
# Resolution is pinned to PHP 8.2 via config.platform in composer.json, so the
# output does not depend on which PHP the machine running this happens to have.

set -euo pipefail

cd "$(dirname "$0")"

SOURCE_DIR="$PWD"
MU_DIR="$PWD/../wp/wp-content/mu-plugins"
TARGET_PAYLOAD="$MU_DIR/wp-alt-streamwrapper"
TARGET_LOADER="$MU_DIR/wp-alt-streamwrapper.php"
CHECK_ONLY=false

if [ "${1:-}" = "--check" ]; then
    CHECK_ONLY=true
fi

STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT
# mktemp gives 0700; the output is copied verbatim into a web-served tree.
chmod 755 "$STAGING"

PAYLOAD="$STAGING/payload"
LOADER="$STAGING/loader.php"
mkdir -p "$PAYLOAD"

echo "==> Installing production dependencies"
cp composer.json composer.lock "$PAYLOAD/"

# Docker first: the AWS SDK requires ext-simplexml, which the host PHP often
# lacks. config.platform pins the PHP version, not the extension set.
if command -v docker >/dev/null 2>&1; then
    # Run as the invoking user so the committed copy isn't root-owned.
    docker run --rm -u "$(id -u):$(id -g)" -e COMPOSER_HOME=/tmp/composer \
        -v "$PAYLOAD:/app" -w /app composer:2 \
        install --no-dev --no-interaction --quiet
elif command -v composer >/dev/null 2>&1; then
    (cd "$PAYLOAD" && composer install --no-dev --no-interaction --quiet)
else
    echo "Need either docker or composer on PATH." >&2
    exit 1
fi

echo "==> Assembling plugin"
cp "$SOURCE_DIR/wp-alt-streamwrapper.php" "$PAYLOAD/"
cp -R "$SOURCE_DIR/bootstrap" "$PAYLOAD/bootstrap"
cp -R "$SOURCE_DIR/src" "$PAYLOAD/src"

cat > "$PAYLOAD/README.txt" <<'EOF'
Generated by wp-alt-streamwrapper/build-plugin.sh — do not edit here.

Edit the plugin in wp-alt-streamwrapper/ at the repository root and re-run
that script. Everything in this directory is overwritten.
EOF

# Same file the E2E compose mounts, so the two can't drift.
cp "$SOURCE_DIR/bootstrap/mu-loader.php" "$LOADER"

if [ "$CHECK_ONLY" = true ]; then
    status=0
    if [ ! -d "$TARGET_PAYLOAD" ] || [ ! -f "$TARGET_LOADER" ]; then
        echo "FAIL: the committed plugin copy is missing." >&2
        status=1
    else
        diff -r "$PAYLOAD" "$TARGET_PAYLOAD" || status=1
        diff "$LOADER" "$TARGET_LOADER" || status=1
    fi

    if [ "$status" -ne 0 ]; then
        echo "FAIL: run ./build-plugin.sh and commit the result." >&2
        exit 1
    fi
    echo "OK: the committed plugin copy is current."
    exit 0
fi

mkdir -p "$MU_DIR"
rm -rf "$TARGET_PAYLOAD"
cp -R "$PAYLOAD" "$TARGET_PAYLOAD"
cp "$LOADER" "$TARGET_LOADER"

echo "==> Built $(find "$TARGET_PAYLOAD" -type f | wc -l) files, $(du -sh "$TARGET_PAYLOAD" | cut -f1) at"
echo "    ${TARGET_PAYLOAD}"
